### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by AndreasAZiegler** [AlexandreCarlton/ycmd-docker#4]
I cloned your repo on my Arch system (kernel  4.19.12) with Python 3.7.1, run ```make images``` successfully and then tried running ```make test```. Unfortunately, ```make test``` fails.

```
make test
docker load --input="ycmd-image.tar"
Loaded image: alexandrecarlton/ycmd:build
# Point to our newly built image when testing.
sed -ri 's|(alexandrecarlton/ycmd)|\1:build|' ycmd-python
python3 tests/example_client.py
Trying to start server...
2018-12-29 20:53:38,553 - INFO - Received ready request
==== Sending event notification ====
tests/example_client.py:251: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance( data, collections.Mapping ):
Traceback (most recent call last):
  File "tests/example_client.py", line 535, in <module>
    Main()
  File "tests/example_client.py", line 516, in Main
    LanguageAgnosticIdentifierCompletion( server )
  File "tests/example_client.py", line 421, in LanguageAgnosticIdentifierCompletion
    filetype = 'javascript' )
  File "tests/example_client.py", line 187, in SendEventNotification
    self.PostToHandlerAndLog( EVENT_HANDLER, request_json )
  File "tests/example_client.py", line 121, in PostToHandlerAndLog
    self._CallHttpie( 'post', handler, data )
  File "tests/example_client.py", line 262, in _CallHttpie
    popen = subprocess.Popen( args, stdin = subprocess.PIPE )
  File "/usr/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'http': 'http'
make: *** [Makefile:41: test] Error 1
```

**Comment by AlexandreCarlton** [comment]
Thanks for the heads up!

Most of this is ripped from the `examples` directory in `ycmd`, this was only included as a basic integration test. I missed the `requirements.txt` file, and now include this when installing. I was able to reproduce this error, and now that I've added the file it no longer appears. `ycmd-docker` should still have been able to function otherwise.

Please let me know if you continue to see the same error. :)

**Comment by AndreasAZiegler** [comment]
Thanks that you addressed the issue so fast. It seems to work now.
